program basic_usage_example;

{$mode DELPHI}

{
  基础使用示例 - 展示 CE Easy Trainer 核心功能

  本示例演示：
  1. 智能持久化地址分析
  2. 创建和管理智能条目
  3. 保存和加载智能表
  4. CT 扩展元数据使用
}

uses
  SysUtils, Classes,
  test_SyntaxCheck,  // 使用独立测试版本（无 CE 依赖）
  CTEasyCompatibilityUnit;

procedure DemoPersistence;
var
  addr: PtrUInt;
  result: TPersistenceResult;
  i: Integer;
begin
  WriteLn('');
  WriteLn('=== 持久化分析示例 ===');
  WriteLn('');

  // 模拟几个不同类型的地址
  for i := 1 to 3 do
  begin
    // 模拟不同基址的地址
    case i of
      1: addr := $140001000;  // 主模块地址
      2: addr := $7FF612340000 + $1000;  // DLL 地址
      3: addr := $12345678;  // 堆地址
    end;

    WriteLn(Format('地址 0x%x:', [addr]));

    // 使用 test_SyntaxCheck 单元的函数
    result := BuildPersistence(addr);

    WriteLn(Format('  策略: %s', [
      '无,指针链,AOB,模块偏移,混合'
    ]));
    WriteLn(Format('  置信度: %.0f%%', [result.Confidence * 100]));
    if result.Method in [pmModuleOffset, pmHybrid] then
      WriteLn(Format('  模块: %s + 0x%x', [result.ModuleName, result.ModuleOffset]));
    WriteLn('');
  end;
end;

procedure DemoSmartTable;
var
  entries: TList;
  entry: PSmartEntry;
  filename: String;
  i: Integer;
begin
  WriteLn('');
  WriteLn('=== 智能表示例 ===');
  WriteLn('');

  entries := TList.Create;
  try
    // 创建几个智能条目
    for i := 1 to 3 do
    begin
      entry := CreateSmartEntry(
        $140001000 + (i * $100),  // 地址
        100 * i,                   // 值
        0,                         // 类型：整数
        Format('Entry %d', [i])    // 描述
      );
      entries.Add(entry);

      WriteLn(Format('创建条目: %s @ 0x%x = %d (置信度: %d%%)',
        [entry^.Description,
         entry^.OriginalAddress,
         entry^.Value,
         entry^.Persistence.Confidence]));
    end;

    // 保存智能表
    filename := 'example_table.smart';
    SaveSmartTable(filename, entries);
    WriteLn('');
    WriteLn(Format('智能表已保存: %s', [filename]));

    // 清空并重新加载
    for i := 0 to entries.Count - 1 do
      Dispose(PSmartEntry(entries[i]));
    entries.Clear;

    LoadSmartTable(filename, entries);
    WriteLn(Format('智能表已加载: %d 个条目', [entries.Count]));

    // 显示加载的条目
    for i := 0 to entries.Count - 1 do
    begin
      entry := PSmartEntry(entries[i]);
      WriteLn(Format('  [%d] %s @ 0x%x = %d',
        [i, entry^.Description,
         entry^.OriginalAddress,
         entry^.Value]));
    end;

  finally
    for i := 0 to entries.Count - 1 do
      Dispose(PSmartEntry(entries[i]));
    entries.Free;
  end;
end;

procedure DemoCTExtension;
var
  xml, xmlWithMeta: String;
  meta, parsed: TCEEasyMetadata;
  success: Boolean;
begin
  WriteLn('');
  WriteLn('=== CT 扩展示例 ===');
  WriteLn('');

  // 示例 CT XML
  xml :=
    '<CheatTable>' +
    '  <CheatEntries>' +
    '    <CheatEntry>' +
    '      <Description>Health</Description>' +
    '      <Address>140001000</Address>' +
    '      <Type>4</Type>' +
    '    </CheatEntry>' +
    '  </CheatEntries>' +
    '</CheatTable>';

  WriteLn('原始 CT XML:');
  WriteLn(xml);
  WriteLn('');

  // 设置元数据
  meta := DefaultMetadata;
  meta.Version := '1.0';
  meta.AutoReattach := True;
  meta.PreferredStrategy := 'hybrid';
  meta.Notes := 'Generated by CE Easy Trainer Example';

  // 注入元数据
  xmlWithMeta := InjectOrUpdateMetadata(xml, meta);
  WriteLn('扩展后的 CT XML:');
  WriteLn(xmlWithMeta);
  WriteLn('');

  // 解析元数据
  success := TryParseMetadata(xmlWithMeta, parsed);
  if success then
  begin
    WriteLn('解析的元数据:');
    WriteLn(Format('  版本: %s', [parsed.Version]));
    WriteLn(Format('  自动重连: %s', [BoolToStr(parsed.AutoReattach, True)]));
    WriteLn(Format('  策略: %s', [parsed.PreferredStrategy]));
    WriteLn(Format('  备注: %s', [parsed.Notes]));
  end
  else
    WriteLn('未能解析元数据');
end;

var
  i: Integer;
begin
  WriteLn('');
  WriteLn('╔════════════════════════════════════════╗');
  WriteLn('║   CE Easy Trainer - 基础使用示例       ║');
  WriteLn('╚════════════════════════════════════════╝');

  DemoPersistence;
  DemoSmartTable;
  DemoCTExtension;

  WriteLn('');
  WriteLn('=== 示例完成 ===');
  WriteLn('');
  WriteLn('下一步:');
  WriteLn('  1. 在 Windows 环境中集成到 CE');
  WriteLn('  2. 使用真实进程地址测试持久化');
  WriteLn('  3. 创建自定义预设和 Trainer');
  WriteLn('');
end.
