program EasyTrainerIntegrationDemo;

{$mode DELPHI}

{
  CE Easy Trainer Integration Demo

  这个程序展示如何将 CE Easy Trainer 核心组件集成到 CE 主程序中。

  集成步骤：
  1. 将以下单元添加到 CE 工程文件 (.lpi/.dpr)：
     - SmartPersistenceUnit
     - EasyTrainerMainUnit
     - CTEasyCompatibilityUnit
     - AutoReattachUnit
     - CEBackendAdapter

  2. 在 MainForm.OnCreate 中初始化：
     procedure TMainForm.FormCreate(Sender: TObject);
     begin
       // ... 现有代码 ...

       // 初始化 Easy Trainer
       InitEasyTrainer;
     end;

  3. 添加定时器（或使用现有定时器）调用 AutoReattach.Tick：
     procedure TMainForm.Timer1Timer(Sender: TObject);
     begin
       // ... 现有代码 ...

       if AutoReattachService <> nil then
         AutoReattachService.Tick;
     end;

  4. 在进程附加后启动自动重连：
     procedure OnProcessOpened(processid: THandle; processhandle: DWORD; caption: string);
     begin
       // ... 现有代码 ...

       if AutoReattachService <> nil then
         AutoReattachService.Start;
     end;
}

interface

implementation

uses
  SysUtils, Classes,
  EasyTrainerMainUnit,
  AutoReattachUnit,
  CTEasyCompatibilityUnit,
  SmartPersistenceUnit;

var
  EasyTrainerController: TEasyTrainerController;
  AutoReattachService: TAutoReattachService;

procedure InitEasyTrainer;
begin
  // 初始化控制器（backend 稍后在 CE 环境中设置）
  EasyTrainerController := TEasyTrainerController.Create(nil);

  // 初始化自动重连服务（probe 稍后设置）
  AutoReattachService := TAutoReattachService.Create('', nil);
  AutoReattachService.MinReattachIntervalTicks := 10; // 10 ticks 间隔

  AutoReattachService.OnLog := procedure(const Msg: String)
  begin
    // 在 CE 中可以将日志输出到状态栏或调试输出
    {$IFDEF WINDOWS}
    OutputDebugString(PChar('[EasyTrainer] ' + Msg));
    {$ENDIF}
  end;

  AutoReattachService.OnReattach := procedure
  begin
    // 重新附加进程并重新应用修改
    if EasyTrainerController <> nil then
    begin
      // 尝试重新附加
      // 实际实现需要获取当前目标进程名
      // EasyTrainerController.Attach(ProcessName);
    end;
  end;
end;

procedure CleanupEasyTrainer;
begin
  if AutoReattachService <> nil then
  begin
    AutoReattachService.Stop;
    AutoReattachService.Free;
    AutoReattachService := nil;
  end;

  if EasyTrainerController <> nil then
  begin
    EasyTrainerController.Free;
    EasyTrainerController := nil;
  end;
end;

// CT 表扩展示例
procedure DemoCTExtension;
var
  xml, xmlWithMeta: String;
  meta, parsedMeta: TCEEasyMetadata;
  success: Boolean;
begin
  // 示例 CT XML
  xml := '<CheatTable>' +
         '  <CheatEntries>' +
         '    <CheatEntry>' +
         '      <Description>Test</Description>' +
         '    </CheatEntry>' +
         '  </CheatEntries>' +
         '</CheatTable>';

  // 设置 Easy Trainer 元数据
  meta := DefaultMetadata;
  meta.Version := '1.0';
  meta.AutoReattach := True;
  meta.PreferredStrategy := 'hybrid';
  meta.Notes := 'Generated by CE Easy Trainer';

  // 注入元数据
  xmlWithMeta := InjectOrUpdateMetadata(xml, meta);

  // 解析元数据
  success := TryParseMetadata(xmlWithMeta, parsedMeta);
  if success then
  begin
    WriteLn('Metadata parsed:');
    WriteLn('  Version: ', parsedMeta.Version);
    WriteLn('  AutoReattach: ', parsedMeta.AutoReattach);
    WriteLn('  Strategy: ', parsedMeta.PreferredStrategy);
    WriteLn('  Notes: ', parsedMeta.Notes);
  end;
end;

initialization
  // 注意：在 CE 环境中，应在 MainForm.OnCreate 中调用 InitEasyTrainer
  // 这里仅作为演示

finalization
  CleanupEasyTrainer;

end.
